### ISSUE TITLE
miner page: increase PAGE_TICK_DURATION_MS

### ISSUE THREAD

**Issue by nitper** [braiins/luci#2]
Would you accept a pull request to increase [`PAGE_TICK_DURATION_MS`](https://github.com/braiins/luci/blob/a4d003ed175216918ad2b65b2e84e6c632a3a036/applications/luci-app-cgminer/luasrc/view/hashrate.htm#L46) to `2000` (or making it configurable)?

Right now if your round-trip latency to the miner is >[900ms](https://github.com/braiins/luci/blob/a4d003ed175216918ad2b65b2e84e6c632a3a036/applications/luci-app-cgminer/luasrc/view/hashrate.htm#L1254), the status page is completely broken.

**Comment by thement** [comment]
Thank you for the offer.
I don't think increasing `PAGE_TICK` is the right way to go - it will sample the data at half the rate for everyone.
I was thinking about how to fix it properly and better way would be to just wait for the request to finish before issuing a new one, and to repeat the last sample in "dead" ticks.
The implementation was just a few lines so I did it and it will be part of the next release.
